Fix race condition in LanguageServerWrapper resulting in NullPointerException during LS initialization (#985)
* Fix race condition resulting in NullPointerException

When running the test suite on Windows a lot of NPEs with the following
stacktrace are thrown:
```
java.lang.NullPointerException: Cannot invoke
"org.eclipse.core.runtime.IProgressMonitor.done()" because
"this.this$0.initializeFutureMonitor" is null
	at org.eclipse.lsp4e.LanguageServerWrapper$2.run(LanguageServerWrapper.java:407)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
and because of the NPE random tests seem to fail.

* improve method name advanceInitializeFutureMonitor

* use UncheckedIOException