Fix erratic NPE in LanguageServersTest#testCancellable
This commit fixes the NPE:

```
org.eclipse.lsp4e.test.LanguageServersTest.testCancellable -- Time
elapsed: 0.112 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke
"org.eclipse.jface.text.ITextViewer.getTextWidget()" because "viewer" is
null
	at org.eclipse.lsp4e.test.LanguageServersTest.testCancellable(LanguageServersTest.java:789)
```

which may occur for the code:
```
IEditorPart editor = TestUtils.openEditor(testFile);
ITextViewer viewer = LSPEclipseUtils.getTextViewer(editor);
IDocument document = viewer.getDocument();
```
where viewer may be null if it has not been initialized fast enough in
the UI thread.