Fixed possible NullPointerExcpetion in DocumentColorProvider
During local tests I saw several times this stacktrace in console:
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4e.operations.color.DocumentColorProvider.lambda$3(DocumentColorProvider.java:64)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)

Change-Id: I7fb6dacdb1b9ab015092c670e955dfbd70e894a8
Signed-off-by: Markus Ofterdinger <markus.ofterdinger@sap.com>